export const poemGenres = [
  { "id": "", "name": "All Genres", "description": "Search across all genres" },
  { "id": 0, "name": "Thơ mới", "description": "Thơ hiện đại, không theo niêm luật cổ điển." },
  { "id": 1, "name": "Lục bát", "description": "Thơ truyền thống Việt Nam, mỗi cặp câu 6-8 chữ." },
  { "id": 2, "name": "Song thất lục bát", "description": "Kết hợp 2 câu 7 chữ với 1 cặp lục bát." },
  { "id": 3, "name": "Ca trù (hát nói)", "description": "Thơ có nhạc điệu, dùng trong ca trù." },
  { "id": 4, "name": "Bốn chữ mới", "description": "Thơ mới, mỗi câu 4 chữ." },
  { "id": 5, "name": "Năm chữ mới", "description": "Thơ mới, mỗi câu 5 chữ." },
  { "id": 6, "name": "Sáu chữ mới", "description": "Thơ mới, mỗi câu 6 chữ." },
  { "id": 7, "name": "Bảy chữ mới", "description": "Thơ mới, mỗi câu 7 chữ." },
  { "id": 8, "name": "Tám chữ mới", "description": "Thơ mới, mỗi câu 8 chữ." },
  { "id": 9, "name": "Tự do", "description": "Không ràng buộc niêm luật, vần." },
  { "id": 10, "name": "Kinh thi", "description": "Tác phẩm thơ cổ Trung Hoa, gốc gác Nho giáo." },
  { "id": 11, "name": "Cổ phong (cổ thể)", "description": "Thơ cổ thể không ràng buộc niêm luật." },
  { "id": 12, "name": "Tứ ngôn", "description": "Thơ 4 chữ, thường dùng trong Kinh thi." },
  { "id": 13, "name": "Ngũ ngôn cổ phong", "description": "Thơ 5 chữ cổ phong, không gò bó vần luật." },
  { "id": 14, "name": "Thất ngôn cổ phong", "description": "Thơ 7 chữ dạng cổ." },
  { "id": 15, "name": "Phú", "description": "Thể văn biền ngẫu, dùng để miêu tả." },
  { "id": 16, "name": "Đường luật", "description": "Thơ luật thời Đường, niêm luật nghiêm ngặt." },
  { "id": 17, "name": "Ngũ ngôn tứ tuyệt", "description": "4 câu, mỗi câu 5 chữ." },
  { "id": 18, "name": "Ngũ ngôn bát cú", "description": "8 câu, mỗi câu 5 chữ." },
  { "id": 19, "name": "Thất ngôn tứ tuyệt", "description": "4 câu, mỗi câu 7 chữ." },
  { "id": 20, "name": "Thất ngôn bát cú", "description": "8 câu, mỗi câu 7 chữ." },
  { "id": 21, "name": "Đường luật biến thể", "description": "Các biến thể từ thể thơ Đường luật." },
  { "id": 22, "name": "Từ phẩm", "description": "Thơ nhạc có điệu thức cố định." },
  { "id": 23, "name": "Tản khúc", "description": "Thơ, nhạc tản mạn, không theo quy chuẩn." },
  { "id": 24, "name": "Câu đối", "description": "Cặp câu đối nhau về ý, vần, và cấu trúc." },
  { "id": 25, "name": "Tản văn", "description": "Văn xuôi ngắn, giàu cảm xúc, chất thơ." },
  { "id": 26, "name": "Thể loại khác (thơ)", "description": "Các thể thơ không phân loại rõ." },
  { "id": 27, "name": "Thể loại khác (ngoài thơ)", "description": "Văn học phi thơ." }
]